### PR TITLE
Pipestat addition 

### PR DESCRIPTION
**Pull request by donaldcampbelljr**
This PR integrates pipestat into pypiper as a means of reporting results.

Wait for:
- [x] Release of pipestat 0.4.0

### CODE REVIEW

**Comment by donaldcampbelljr** [comment]
Related to:
https://github.com/pepkit/pipestat/issues/21

**Comment by donaldcampbelljr** [comment]
This needs the latest dev branch from pipestat as well as yacman to run properly.

`pip install git+https://github.com/databio/yacman.git@dev`
`pip install git+https://github.com/pepkit/pipestat@dev#egg=pipestat`

**Comment by donaldcampbelljr** [comment]
**Some action items:**
- [ ] Remove report_object (simply use report_result)
- [ ] Remove wrapping of key, value within report_result
- [ ] Move markdown reporting to pipestat.

**Review by nsheff — COMMENTED** [review]
thinking about this -- to maintain backwards compatibility, we probably want to retain `report_object`, but just have it operate through the new `report_result`.

Otherwise, all existing pypiper pipelines will break.

**Comment by donaldcampbelljr** [comment]
OK, I added it back in and kept the original parameters but it will use `pipestat.report `to actually report. I also added a deprecation warning.

**Comment by nsheff** [comment]
> OK, I added it back in and kept the original parameters but it will use `pipestat.report `to actually report. I also added a deprecation warning.

that's perfect

**Comment by donaldcampbelljr** [comment]
Markdown formatting was moved to pipestat, but the formatted will be returned to pypiper for logging purposes.

**Comment by donaldcampbelljr** [comment]
pipestat 0.4.0 now released and all tests are passing, merging.

**Pull request merged**
