### PR TITLE
release 0.11.0

### PR DESCRIPTION
**Pull request by nsheff**

### CODE REVIEW

**Comment by nsheff** [comment]
Ok this is working for me with pepatac all the way through on python 3 now. So I'm ready to merge this as soon as you are ready @michalstolarczyk

**Comment by nsheff** [comment]
Ready for release, any objections?

**Comment by michalstolarczyk** [comment]
The command ID tracking does not work (in some cases) as indicated in #151 

You can take it out for this release or we can work on it and include in the next version

**Comment by nsheff** [comment]
can you just remove the counting of all follow functions pretty easily?

**Comment by nsheff** [comment]
in absence of that, I'd say just release it in its current semi-functional state... it's still useful in some cases. as long as it doesn't cause failures.

**Comment by michalstolarczyk** [comment]
now all the follow functions do not increment the counter. Those that are run using `run` method are reported in the profile with <previousID>f.

**Pull request merged**
